config/routes.rb
ExampleAppointments::Application.routes.draw do
  resources :appt_uploads

  resources :appt_scheds
  
  root 'appt_scheds#index'

end

app/models/appt_upload.rb
class ApptUpload < ActiveRecord::Base
  validates :content, presence: true #, format: { with: $RE_SIMPLE_CSV_CONTENT } 
  validate :content_in_correct_format
  
private  
  def content_in_correct_format
    msg = "Required format for rows: datetime,datetime,name,name,comment; where comment is optional, datetime is mm/dd/yyyy hh:mm, and name and comment only contain 'word' characters such as A-Z, a-z, 0-9, and '_'. (Header row is considered line # 0.)"
    
    has_error = false
    
    if (content)
      # errors.add(:content, "Required format for rows: datetime,datetime,name,name,comment; where comment is optional, datetime is mm/dd/yyyy hh:mm, and name and comment only contain 'word' characters such as A-Z, a-z, 0-9, and '_'.") unless ($RE_SIMPLE_CSV_LINE.match(content))
      content.gsub!("\r\n","\n")
      lines = content.split("\n")
      
      len = lines.length
      unless (len >= 2)
        has_error = true
        msg += " [ERROR: Missing data. First line should be header, followed by data lines. # of lines: #{len}]"
      else
        (1..(len-1)).each do |ln|
          line = lines[ln]
              
          line_parts = line.split(',')
          Rails.logger.info " # #{ln}: line_parts == #{line_parts}"
          
          line_parts_len = line_parts.length
          Rails.logger.info " # #{ln}: line_parts_len == #{line_parts_len}"
          
          unless (line_parts_len == 4 || line_parts_len == 5)
            has_error = true
            msg += " [ERROR: Wrong number of columns: #{line_parts_len} in line #: #{ln}.]"
          else
            comments = nil
            start_time, end_time, first_name, last_name = line_parts[0..4] if (line_parts_len = 4)
            start_time, end_time, first_name, last_name, comments = line_parts[0..4] if (line_parts_len = 5)
              
            Rails.logger.info " # #{ln}: line_parts : #{[start_time, end_time, first_name, last_name, comments]}"
            
              
            Rails.logger.info " # #{ln}: from, to : #{[DateTime.parse(start_time), DateTime.parse(end_time)]}"
            
            begin
              s = ApptSched.new
              # s.start_time = start_time
              s.start_time = DateTime.parse(start_time)

              # s.end_time = end_time
              s.end_time = DateTime.parse(end_time)
              
              s.first_name = first_name
              s.last_name = last_name
              s.comments = comments
              s.save!
            rescue Exception => e
              has_error = true
              msg += " [ERROR: ApptSched data error: #{e.message} in line #: #{ln}.]"
            end
            
          end
          
        end
        
      end
      
      
      Rails.logger.info "has_error == #{has_error}"
      
      errors.add(:content, msg) if has_error
      
    end    
  end
end

=begin

    $RE_SIMPLE_DATETIME = /\A[0-9\/]+\s[0-9:]+\z/
    $RE_SIMPLE_NAME = /\A(\w+)(\s+\w+)*\z/
    $RE_SIMPLE_COMMENT = /(\A(\w+)(\s+\w+)*\z)*/
    $RE_SIMPLE_CSV_LINE = /\A([0-9\/]+\s[0-9:]+),([0-9\/]+\s[0-9:]+),((\w+)(\s+\w+)*),((\w+)(\s+\w+)*),((\w+)(\s+\w+)*)?\z/
    $RE_SIMPLE_CSV_HEADER = /\A((\w+)(\s+\w+)*),((\w+)(\s+\w+)*),((\w+)(\s+\w+)*),((\w+)(\s+\w+)*),((\w+)(\s+\w+)*)?\z/
    $RE_SIMPLE_CSV_CONTENT = /(\A((\w+)(\s+\w+)*),((\w+)(\s+\w+)*),((\w+)(\s+\w+)*),((\w+)(\s+\w+)*),((\w+)(\s+\w+)*)?\z)?(\A([0-9\/]+\s[0-9:]+),([0-9\/]+\s[0-9:]+),((\w+)(\s+\w+)*),((\w+)(\s+\w+)*),((\w+)(\s+\w+)*)?\z)+/
    
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :first_name, presence: true, format: { with: $RE_SIMPLE_NAME } # TODO: not a stated requirement, but probably should be.
  validates :last_name, presence: true, format: { with: $RE_SIMPLE_NAME } # TODO: not a stated requirement, but probably should be.
  validates :comments, format: { with: $RE_SIMPLE_COMMENT } # TODO: not a stated requirement, but probably should be.
  
=end

app/controllers/appt_uploads_controller.rb
class ApptUploadsController < ApplicationController
  before_action :set_appt_upload, only: [:show, :edit, :update, :destroy]

  # GET /appt_uploads
  # GET /appt_uploads.json
  def index
    @appt_uploads = ApptUpload.all
  end

  # GET /appt_uploads/1
  # GET /appt_uploads/1.json
  def show
  end

  # GET /appt_uploads/new
  def new
    @appt_upload = ApptUpload.new
  end

  # GET /appt_uploads/1/edit
  def edit
  end

  # POST /appt_uploads
  # POST /appt_uploads.json
  def create
    @appt_upload = ApptUpload.new(appt_upload_params)

    respond_to do |format|
      if @appt_upload.save
        format.html { redirect_to @appt_upload, notice: 'Appt upload was successfully created.' }
        format.json { render action: 'show', status: :created, location: @appt_upload }
      else
        format.html { render action: 'new' }
        format.json { render json: @appt_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appt_uploads/1
  # PATCH/PUT /appt_uploads/1.json
  def update
    respond_to do |format|
      if @appt_upload.update(appt_upload_params)
        format.html { redirect_to @appt_upload, notice: 'Appt upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @appt_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appt_uploads/1
  # DELETE /appt_uploads/1.json
  def destroy
    @appt_upload.destroy
    respond_to do |format|
      format.html { redirect_to appt_uploads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appt_upload
      @appt_upload = ApptUpload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appt_upload_params
      params.require(:appt_upload).permit(:process_start_time, :process_end_time, :content)
    end
end

app/helpers/appt_uploads_helper.rb
module ApptUploadsHelper
end

app/views/appt_uploads/_form.html.erb
<%= form_for(@appt_upload) do |f| %>
  <% if @appt_upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appt_upload.errors.count, "error") %> prohibited this appt_upload from being saved:</h2>

      <ul>
      <% @appt_upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :cols => "80", :rows => "20" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appt_uploads/edit.html.erb
<h1>Editing appt_upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @appt_upload %> |
<%= link_to 'Back', appt_uploads_path %>

app/views/appt_uploads/index.html.erb
<h1>Listing appt_uploads</h1>

<table>
  <thead>
    <tr>
      <th>Process start time</th>
      <th>Process end time</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @appt_uploads.each do |appt_upload| %>
      <tr>
        <td><%= appt_upload.process_start_time %></td>
        <td><%= appt_upload.process_end_time %></td>
        <td><%= appt_upload.content %></td>
        <td><%= link_to 'Show', appt_upload %></td>
        <td><%= link_to 'Edit', edit_appt_upload_path(appt_upload) %></td>
        <td><%= link_to 'Destroy', appt_upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appt upload', new_appt_upload_path %>

app/views/appt_uploads/new.html.erb
<h1>New appt_upload</h1>

<%= render 'form' %>

<%= link_to 'Back', appt_uploads_path %>

app/views/appt_uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Process start time:</strong>
  <%= @appt_upload.process_start_time %>
</p>

<p>
  <strong>Process end time:</strong>
  <%= @appt_upload.process_end_time %>
</p>

<p>
  <strong>Content:</strong>
  <%= @appt_upload.content %>
</p>

<%= link_to 'Edit', edit_appt_upload_path(@appt_upload) %> |
<%= link_to 'Back', appt_uploads_path %>