config/routes.rb
ExampleAppointments::Application.routes.draw do
  resources :appt_uploads

  resources :appt_scheds
  
  root 'appt_scheds#index'

end

app/models/appt_sched.rb
class ApptSched < ActiveRecord::Base
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :first_name, presence: true, format: { with: $RE_SIMPLE_NAME } # TODO: not a stated requirement, but probably should be.
  validates :last_name, presence: true, format: { with: $RE_SIMPLE_NAME } # TODO: not a stated requirement, but probably should be.
  validates :comments, format: { with: $RE_SIMPLE_COMMENT } # TODO: not a stated requirement, but probably should be.
  
  validate :start_before_end
  validate :start_after_now
  validate :end_after_now
  validate :start_does_not_overlap
  validate :end_does_not_overlap

private  
  def start_before_end
    if (start_time && end_time)
      errors.add(:end_time, "start_time should be before end_time") if (start_time > end_time)
    end    
  end
  
  def start_after_now
    if (start_time)
      # errors.add(:start_time, "start_time should be in future") if (start_time < Time.now)
      errors.add(:start_time, "start_time should be in future") if (start_time < Time.now)
    end    
  end
  
  def end_after_now
    if (end_time)
      # errors.add(:start_time, "start_time should be in future") if (start_time < Time.now)
      errors.add(:end_time, "end_time should be in future") if (end_time < Time.now)
    end    
  end
  
  def start_does_not_overlap
    if (start_time)
      errors.add(:start_time, "start_time should not overlap existing records") if (ApptSched.exists?(["(start_time <= ?) AND (? <= end_time)", start_time, start_time]))
    end    
  end
  
  def end_does_not_overlap
    if (end_time)
      errors.add(:end_time, "end_time should not overlap existing records") if (ApptSched.exists?(["(start_time <= ?) AND (? <= end_time)", end_time, end_time]))
    end    
  end

end

app/controllers/appt_scheds_controller.rb
class ApptSchedsController < ApplicationController
  before_action :set_appt_sched, only: [:show, :edit, :update, :destroy]

  # GET /appt_scheds
  # GET /appt_scheds.json
  def index
    @appt_scheds = ApptSched.all
  end

  # GET /appt_scheds/1
  # GET /appt_scheds/1.json
  def show
  end

  # GET /appt_scheds/new
  def new
    @appt_sched = ApptSched.new
  end

  # GET /appt_scheds/1/edit
  def edit
  end

  # POST /appt_scheds
  # POST /appt_scheds.json
  def create
    @appt_sched = ApptSched.new(appt_sched_params)

    respond_to do |format|
      if @appt_sched.save
        format.html { redirect_to @appt_sched, notice: 'Appt sched was successfully created.' }
        format.json { render action: 'show', status: :created, location: @appt_sched }
      else
        format.html { render action: 'new' }
        format.json { render json: @appt_sched.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appt_scheds/1
  # PATCH/PUT /appt_scheds/1.json
  def update
    respond_to do |format|
      if @appt_sched.update(appt_sched_params)
        format.html { redirect_to @appt_sched, notice: 'Appt sched was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @appt_sched.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appt_scheds/1
  # DELETE /appt_scheds/1.json
  def destroy
    @appt_sched.destroy
    respond_to do |format|
      format.html { redirect_to appt_scheds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appt_sched
      @appt_sched = ApptSched.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appt_sched_params
      params.require(:appt_sched).permit(:start_time, :end_time, :first_name, :last_name, :comments)
    end
end

app/helpers/appt_scheds_helper.rb
module ApptSchedsHelper
end

app/views/appt_scheds/_form.html.erb
<%= form_for(@appt_sched) do |f| %>
  <% if @appt_sched.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appt_sched.errors.count, "error") %> prohibited this appt_sched from being saved:</h2>

      <ul>
      <% @appt_sched.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %> (UTC)<br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %> (UTC)<br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_field :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appt_scheds/edit.html.erb
<h1>Editing appt_sched</h1>

<%= render 'form' %>

<%= link_to 'Show', @appt_sched %> |
<%= link_to 'Back', appt_scheds_path %>

app/views/appt_scheds/index.html.erb
<h1>Listing appt_scheds</h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Comments</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @appt_scheds.each do |appt_sched| %>
      <tr>
        <td><%= appt_sched.start_time %></td>
        <td><%= appt_sched.end_time %></td>
        <td><%= appt_sched.first_name %></td>
        <td><%= appt_sched.last_name %></td>
        <td><%= appt_sched.comments %></td>
        <td><%= link_to 'Show', appt_sched %></td>
        <td><%= link_to 'Edit', edit_appt_sched_path(appt_sched) %></td>
        <td><%= link_to 'Destroy', appt_sched, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appt sched', new_appt_sched_path %>

app/views/appt_scheds/new.html.erb
<h1>New appt_sched</h1>

<%= render 'form' %>

<%= link_to 'Back', appt_scheds_path %>

app/views/appt_scheds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @appt_sched.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @appt_sched.end_time %>
</p>

<p>
  <strong>First name:</strong>
  <%= @appt_sched.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @appt_sched.last_name %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @appt_sched.comments %>
</p>

<%= link_to 'Edit', edit_appt_sched_path(@appt_sched) %> |
<%= link_to 'Back', appt_scheds_path %>